### ISSUE TITLE
编译第2、3个机型时出错

### ISSUE THREAD

**Issue by DaPoHou** [hugcabbage/shared-lede#1]
Run ./scripts/feeds update -a
/home/runner/work/_temp/b2fab536-2f2c-4fd2-9284-b795fe4b4eea.sh: line 1: ./scripts/feeds: No such file or directory

**Comment by hugcabbage** [comment]
已经修复 https://github.com/hugcabbage/shared-lede/commit/a6d92e643c5685253ffe528e6b9cfb2b1dc0ad90
