### ISSUE TITLE
编译CR6608出包后上传机型提示不匹配

### ISSUE THREAD

**Issue by mxfj** [hugcabbage/shared-lede#10]
root@OpenWrt:/tmp# sysupgrade openwrt-ramips-mt7621-xiaomi_mi-router-cr6608-squashfs-sysupgrade.bin 
Wed Jun 15 17:21:31 CST 2022 upgrade: Device xiaomi,mi-router-cr660x not supported by this image
Wed Jun 15 17:21:31 CST 2022 upgrade: Supported devices: xiaomi,mi-router-cr6608
Image check failed.

**Comment by hugcabbage** [comment]
不是同一个源码，请从pb-boot刷入
