### ISSUE TITLE
在编译cr6609版本时是出现error，Hunk #1 FAILED at 706.

### ISSUE THREAD

**Issue by Qinyz910** [hugcabbage/shared-lede#15]
Hunk #1 FAILED at 706.
Hunk #2 succeeded at 3752 (offset -34 lines).
1 out of 2 hunks FAILED -- saving rejects to file net/netfilter/nf_conntrack_netlink.c.rej
Patch failed!  Please fix /home/runner/work/shared-lede/shared-lede/target/linux/generic/hack-5.10/952-net-conntrack-events-support-multiple-registrant.patch!
make[3]: *** [Makefile:123: /home/runner/work/shared-lede/shared-lede/build_dir/toolchain-mipsel_24kc_gcc-11.3.0_musl/linux-5.10.138/.prepared] Error 1
make[3]: Leaving directory '/home/runner/work/shared-lede/shared-lede/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#12.88#6.33#15.76
    ERROR: toolchain/kernel-headers failed to build.
make[2]: Leaving directory '/home/runner/work/shared-lede/shared-lede'
make[2]: *** [toolchain/Makefile:97: toolchain/kernel-headers/compile] Error 1
make[1]: *** [toolchain/Makefile:93: /home/runner/work/shared-lede/shared-lede/staging_dir/toolchain-mipsel_24kc_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/runner/work/shared-lede/shared-lede'
make: *** [/home/runner/work/shared-lede/shared-lede/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by hugcabbage** [comment]
952-net-conntrack-events-support-multiple-registrant.patch
这个补丁的问题，等源码作者更新修复哦，可以先用5.15内核的 @Qinyz910
