### ISSUE TITLE
修改源之后编译失败

### ISSUE THREAD

**Issue by ccculing** [hugcabbage/shared-lede#17]
把固件源换成了https://github.com/coolsnowwolf/lede，
添加了两个插件alist、onliner
![image](https://user-images.githubusercontent.com/103477836/190881046-03ae3a27-dbeb-43fb-9259-a2a1a683b35d.png)

**Comment by hugcabbage** [comment]
自行把对应的modify.sh中的修改zzz-default-settings的几行注释掉 @ccculing

**Comment by ccculing** [comment]
OK
