### ISSUE TITLE
请问为什么编译成功后，在op里无法更新？

### ISSUE THREAD

**Issue by ccculing** [hugcabbage/shared-lede#18]
![image](https://user-images.githubusercontent.com/103477836/191294773-04860dde-13cd-4300-a658-7eb816dc151d.png)
![image](https://user-images.githubusercontent.com/103477836/191295208-12ea7264-5e8f-4646-a9c0-1dfebd3f7a8e.png)
是我哪里设置不对吗？

**Comment by hugcabbage** [comment]
你这个包名不对啊，都不是同一个机型
