### ISSUE TITLE
默认+超频编译cr6606后刷入，帕斯沃2无法启动

### ISSUE THREAD

**Issue by JohnRowton** [hugcabbage/shared-lede#19]
如题所述

**Comment by hugcabbage** [comment]
你查看对应软件的日志看看

**Comment by JohnRowton** [comment]
打开总开关后，日志没有任何显示，是因为默认的依赖没有勾全有关吗？

**Comment by JohnRowton** [comment]
系统未安装iptables或ipset，无法透明代理

**Comment by hugcabbage** [comment]
> 系统未安装iptables或ipset，无法透明代理

那你把config文件里的Transparent_Proxy选上

**Comment by JohnRowton** [comment]
查找到的原因是iptables没有安装，自带软件源里也没有

**Comment by hugcabbage** [comment]
> 查找到的原因是iptables没有安装，自带软件源里也没有

https://github.com/xiaorouji/openwrt-passwall2/issues/137
https://github.com/xiaorouji/openwrt-passwall2/issues/159
